apiVersion: v1
kind: Pod
metadata:
  name: declarative-pod
  labels:
    name: appname
spec:
  containers:
  - name: appname
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
